chatGpt:
  apiKey: sk-xxxx
  apiUrl: https://api.openai.com
  imageDir: /data/qqbot/images
  model: gpt-4o-mini
  session:
    messageLimit: 32
    expireSeconds: 600
qqBot:
  id: 1000000
  ws:
    addr: 127.0.0.1
    port: 3001
  zero:
    commandPrefix: /
    nickNames:
      - 小诗
    superUsers:
      - 2000000
  webGui:
    host: 127.0.0.1
    port: 8080